### ISSUE TITLE
Idea - Question - Discussion - Using memlab to refactor code targeting different framework philosphy

### ISSUE THREAD

**Issue by imvetri** [facebook/memlab#102]
Problem in most of the projects is maintenance, and framework dependency. while there are multiple frameworks out there, community would enjoy a tool that would help them refactor current source code base to a targeted framework.

In my opinion memlab, helps in many ways like tracing data sources, initially I checked memlab thinking that it is a static code analyser, turns out it is other wise.

Sharing an abstract idea, to see where it heads.

**Comment by JacksonGL** [comment]
@imvetri I'm not sure I understand the idea here. Could you elaborate it a little bit more? MemLab is a tool designed for identifying JavaScript memory leaks and pinpointing opportunities for optimization. It does not serve as a static code refactoring tool.
