### ISSUE TITLE
老哥有点问题，本地默认安装你的仓库里面有个依赖包引入 colors 的包默认是1.4.2的 被污染的那个包  导致 启动不起来，windows 开发环境，

### ISSUE THREAD

**Issue by susakin** [facebook/memlab#104]

**Comment by JacksonGL** [comment]
@susakin memlab does not directly import the colors package. `npm install memlab` should not install colors@1.4.2 if it doesn't exist (I only see [colors@1.4.0 as the latest version](https://www.npmjs.com/package/colors?activeTab=versions), perhaps it gets removed recently I don't know). I would recommend delete the `package-lock.json` file, delete the entire `node_modules` directory, and reinstall memlab (works for me on Windows).

**Comment by susakin** [comment]
thx ,there is some problem on npm mirror ，in our company‘s npm still has 1.4.2 version colors
