### ISSUE TITLE
core_1.browserInfo.setPuppeteerConfig is not a function

### ISSUE THREAD

**Issue by DaveMBush** [facebook/memlab#109]
When running this script:

``` typescript
import * as memlab from 'memlab';
import { scenario as demoStandard } from './demo/base-line-to-tree';

(async function () {
  // I've also tried importing run from @memlab/core and using it instead of
  // memlab.run(...)
  const { leaks, runResult } = await memlab.run({ scenario: demoStandard });
  if (leaks.length > 0) {
    console.log(
      runResult.getRunMetaInfo().browserInfo._consoleMessages.join('\n'),
    );
  } else {
    console.log('No leaks detected');
  }
  runResult.cleanup();
})();
```

I get output while it is running `memlab.run(...)` and then the error:

> `core_1.browserInfo.setPuppeteerConfig is not a function`

![image](https://github.com/facebook/memlab/assets/10533667/a41c544e-7920-4720-b5a3-f84b99a1d1d8)

I've run with the debugger and it never hits the `if(leaks.length)` line.

The error sounds like a puppeteer version mismatch but I've verified I don't have any version of puppeteer other than what memlab installs and they are all the same version.

The file I'm working in is located here if it helps track down what I'm doing wrong:
https://github.com/DaveMBush/SmartNgRX/blob/dmb/add-additional-memlab-tests/286/apps/demo-memlab/src/memlab/main.ts

Finally, I'm moving from using the cli to using a node script. The cli version works which you can view by looking at the `main` branch.  So the only new packages are the @memlab packages I had to install for the script.  I've also moved to typescript instead of plain javascript so I can run the code with ts-node.

Any help at all would be greatly appreciated.

**Comment by JacksonGL** [comment]
@DaveMBush Looks like your `@memlab/core` package is outdated. In the latest version of MemLab, an internal method called `setPuppeteerConfig` was renamed. I would recommend clean all the @memlab/* packages in `node_modules` directory and reinstall memlab.

**Comment by DaveMBush** [comment]
Actually, it was @memlab/api.  I must have grabbed that one just before the change as it is the only one that wasn't using the most recent version.

Thanks for the fast reply to a stupid question.
