### ISSUE TITLE
Is there a way to run in scripting mode using silent?

### ISSUE THREAD

**Issue by DaveMBush** [facebook/memlab#110]
The CLI has a --silent option.

when running using script mode:

``` typescript
    const { leaks, runResult } = await run({
      scenario,
      skipWarmup,
      workDir,
    });
```

Is there a way to do the same? 

I've tried

``` typescript
  process.argv.push('--silent');
```

But it had no effect.

**Comment by JacksonGL** [comment]
Consider using the following code to run in silent mode.

```
const {config} = require('@memlab/core');
config.muteConsole = true;
```

We can also add an additional option for the `run` API.

**Comment by DaveMBush** [comment]
I just tried the above and I'm still seeing console output.

**Comment by JacksonGL** [comment]
@DaveMBush can you provide the code you use?

For example running `node test.js` shows no output on my machine:
```javascript
// save as test.js
const {run} = require('@memlab/api');
const {config} = require('@memlab/core');
config.muteConsole = true;

(async function () {
  const scenario = {
    url: () => 'https://www.facebook.com',
  };
  const {leaks} = await run({scenario});
})();
```

`test.js` is located inside a npm project where it has run `npm i memlab`.

**Comment by DaveMBush** [comment]
Thanks.  I found it.  I was using `config.isContinuousTest = true;` as well and that seems to override `config.muteConsole`

Thanks again for your help.
