### ISSUE TITLE
Keep `@memlab/*` versions in lockstep in package.json

### ISSUE THREAD

**Issue by jeswr** [facebook/memlab#113]
I've recently encountered the error `core_1.browserInfo.recordPuppeteerConfig` is not a function. This is similar to https://github.com/facebook/memlab/issues/109; and it was encountered in an automated dependabot update (https://github.com/eyereasoner/eye-js/pull/831).

Indeed running `npm upgrade` to bump the version of `@memlab/core` fixes the issue; but really I would expect that if `@memlab/api` uses APIs [introduced in v1.1.27 of `@memlab/core`](https://github.com/facebook/memlab/commit/fb6c134256b708a022ed999d4261a96920d3db9a) then `@memlab/api` should depend on at minimum ^1.1.27 of `@memlab/core` in the package.json as opposed to v1.1.10 which it is currently set at https://github.com/facebook/memlab/blob/bb1a3b6b8d54e127fab1ede768adbd9078d35633/packages/api/package.json#L30-L32 as this would then ensure that tooling like npm and dependabot will upgrade such dependencies in downstream lockfiles when trying to upgrade the version of `@memlab/api`.

Monorepo tooling such as [lerna](https://github.com/lerna/lerna) has native support for this kind of lockstep versioning.

**Comment by JacksonGL** [comment]
Thank you for reporting this issue. I have updated the minimum version of dependency and publish the latest version (`memlab@1.1.45`).
