### ISSUE TITLE
Clarify the documentation about measure mode

### ISSUE THREAD

**Issue by mrdulin** [facebook/memlab#116]
After reading the [`memlab measure`](https://facebook.github.io/memlab/docs/cli/CLI-commands#memlab-measure) documentation ten times, I still don't know what it is.

So I read the source code of [MeasureMode.ts](https://github.com/facebook/memlab/blob/19ef63ac5093a83398615bdd02104e1952046fdc/packages/core/src/modes/MeasureMode.ts#L20) file.

Does that mean if run the scenario in measure mode, `memlab` will **not**:

- Take screenshots
- Take heap snapshots
- Extra wait for Target (which I also don't know what it means.)
- Extra target operations (it seems it is equivalent to the `--skip-extra-ops` option, which documentation is not clear either)

When I run in measure mode, it seems `memlab` will run the scenario 10 times.

```bash
$ npx memlab measure --scenario tests/detached-DOM-elements/index.js
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.7s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.5s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.6s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.6s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.5s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.6s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.5s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.5s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.6s
page-load[1.8MB](baseline)[s1] > action-on-page[2.1MB](target)[s2] > revert[2.3MB](final)[s3]

total time: 46.6s
```

Please clarify the documentation, what's the measure mode and what are the usage scenarios for the measure mode?

**Comment by JacksonGL** [comment]
In some web apps, the heap size can show considerable variability across various runs. This fluctuation can often make it hard to understand the impact of memory leaks. The introduction of the measure mode aims to address this challenge by executing the same scenario repetitively, therefore getting multiple data points of JavaScript heap sizes. This can help understand if the heap size movements during specific runs come from memory-related issues or just noises.

**Comment by mrdulin** [comment]
@JacksonGL 这很有帮助。这些解释应该添加到文档中。如果有例子就更好了。

**Comment by JacksonGL** [comment]
Those are good feedback, thanks. The GitHub repo discussion is now open.
