### ISSUE TITLE
How can I use script_id in IHeapLocation to get js url ？

### ISSUE THREAD

**Issue by shimingw** [facebook/memlab#118]
Is there any way I can get the js url of the specified node？

**Comment by shimingw** [comment]
Is there any way I can get the js url of the specified node？

**Comment by JacksonGL** [comment]
From what I understand, `script_id` in `IHeapLocation` is just an index referring to a data structure in Chrome's memory when the heap snapshot was taken, but Chrome does not seem to encode and serialize the index to URL mapping in JS heap snapshot.

**Comment by shimingw** [comment]
Thank you for your reply
