### ISSUE TITLE
RangeError: Invalid string length in LeakTraceDetailsLogger

### ISSUE THREAD

**Issue by johnhok** [facebook/memlab#121]
## Error

I'm getting this an `RangeError: Invalid string length` when I run `memlab` in a CI environment.

![Screenshot 2024-06-28 at 10 10 43 AM](https://github.com/facebook/memlab/assets/1030271/28652b35-0d7e-48e1-a06d-99857ed139f4)

It looks to be related to `JSON.stringify` in the `LeakTraceDetailsLogger`.

https://github.com/facebook/memlab/blob/16b4d9a3f1d383b02a67a4d87596f8a16c0d1f86/packages/core/src/logger/LeakTraceDetailsLogger.ts#L44

## Notes

- While digging around, it generally looks like this is an OOM in node when trying to stringify a large object. I've tried tweaking the execution environment to increase memory but have been unsuccessful in resolving.
- Unfortunately, I've also been unable to reproduce this on my local machine and I've been unable to extract the heap snapshots that generates this specific error (for other reasons).
- The heap dumps don't seem particularly complex from the sizes 
    - ex. `page-load[27.5MB](baseline)[s1] > action-on-page[62MB](target)[s2] > revert[59.1MB](final)[s3]`

Does anyone have thoughts on alternative solutions to resolve this or have encountered a similar situation?

**Comment by JacksonGL** [comment]
`RangeError: Invalid string length` indicates that the string is too large, causing the JavaScript engine to throw an exception. Since the `traceJSON` result is not critical for most use cases, you can temporarily resolve this issue by commenting out the `JSON.stringify` statement and replacing it with something like:
```javascript
const traceJSON = {};
```
I will add a guard check to this statement later.

**Comment by johnhok** [comment]
Are you planning on bumping the memlab versions? I see you have the proper fix in place now. Thanks for the help!

**Comment by JacksonGL** [comment]
@johnhok The fix is released in `memlab@1.1.49`.
