### ISSUE TITLE
Ask about the relevant knowledge of find-leaks API.

### ISSUE THREAD

**Issue by boliangleung** [facebook/memlab#132]
1. The result of find-leaks can be output to a detailed file, or type'memlab analyze detected-DOM --snapshot./test1.heapsnapshot --output text 'detailed content is output in text form

![image](https://github.com/user-attachments/assets/123d600b-a807-4abc-9865-33e15adfe63e)

2. I want to write a plugin to use find-leaks to process parsed data. Is there any idea for this?

Looking forward to your answer！！！

**Comment by JacksonGL** [comment]
@boliangleung 

> The result of find-leaks can be output to a detailed file, or type'memlab analyze detected-DOM --snapshot./test1.heapsnapshot --output text 'detailed content is output in text form

Are you suggesting adding a new option flag to specify the output file?

> I want to write a plugin to use find-leaks to process parsed data. Is there any idea for this?

I don't quite understand your question. Could you provide more details about this?

**Comment by JacksonGL** [comment]
Closing this issue due to lack of clarification. Please feel free to reopen with more details.
