### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RonNachmany** [facebook/memlab#19]
Got - RangeError: Maximum call stack size exceeded error while doing Getting Started tutorial.

**Comment by JacksonGL** [comment]
I wasn't able to reproduce the error if you were running the command in this [tutorial page](https://facebookincubator.github.io/memlab/docs/getting-started).

Can you share the error message including the stack trace? What is the OS version and node version are you using?

**Comment by JacksonGL** [comment]
Unable to reproduce, closing it now

**Comment by gaoyuanfell** [comment]
![image](https://user-images.githubusercontent.com/21239565/190961637-1420668d-d869-463d-9f21-37f595df0e1b.png)

**Comment by gaoyuanfell** [comment]
![image](https://user-images.githubusercontent.com/21239565/190965416-f5108477-bf71-459f-8f5f-a18bbf70890f.png)
这个是不一样的错误，看下对你们有没有帮助
