### ISSUE TITLE
Is it possible to set browser headers for each scenario?

### ISSUE THREAD

**Issue by willemliufdmg** [facebook/memlab#42]
I was searching through the docs but couldn't find a way to set request headers for each scenario to use.

Is there a way to set request headers?

**Comment by JacksonGL** [comment]
@willemliufdmg Does calling [`page.setExtraHTTPHeaders`](https://pptr.dev/next/api/puppeteer.page.setextrahttpheaders) inside the [`setup` callback](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback) work for your use case?

**Comment by willemliufdmg** [comment]
> @willemliufdmg Does calling [`page.setExtraHTTPHeaders`](https://pptr.dev/next/api/puppeteer.page.setextrahttpheaders) inside the [`setup` callback](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback) work for your use case?

Thank you for the suggestion. I'll give it a try today and get back to you.

**Comment by willemliufdmg** [comment]
> @willemliufdmg Does calling [`page.setExtraHTTPHeaders`](https://pptr.dev/next/api/puppeteer.page.setextrahttpheaders) inside the [`setup` callback](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback) work for your use case?

This works well! Thank you for the solution!

**Comment by willemliufdmg** [comment]
> @willemliufdmg Does calling [`page.setExtraHTTPHeaders`](https://pptr.dev/next/api/puppeteer.page.setextrahttpheaders) inside the [`setup` callback](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback) work for your use case?

At first I thought it was working. But I was looking at the wrong thing. Sadly your suggestion doesn't work as the headers are set _after_ initial page load with this method.

I wanted to set headers so it's being sent with every request.

**Comment by JacksonGL** [comment]
We may be able to add a new callback before the initial page load (something like `beforeInitialLoad(page)`)

**Comment by willemliufdmg** [comment]
> We may be able to add a new callback before the initial page load (something like `beforeInitialLoad(page)`)

That would be great. Then it would be possible to add headers or whatever else is necessary before a page request has been sent.

**Comment by JacksonGL** [comment]
New API: https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-beforeinitialpageload-interactionscallback
