### ISSUE TITLE
how to position qiankun + vue2 leaked code?

### ISSUE THREAD

**Issue by HHH1994** [facebook/memlab#50]
hello, i used memlab to detect my project which is coded by Vue2 + qiankun,  find some leaks.but trace info is almost complied code that variable's name is not similar to origin code .  can u give me some help to solve  the  problem that is too difficult to detected leaked code's position in  webapck service?  thanks 
![mmexport1667874851257](https://user-images.githubusercontent.com/24916262/200461353-7b4ac2db-0461-4917-8b59-2f60635e8095.jpg)

**Comment by JacksonGL** [comment]
Hi @HHH1994 To get readable trace, the website under test needs to serve non-minified code (or at least minified code with readable variables, function name, and property names on objects). I remember there is an option in webpack to turn off minification. Something like:
```js
{
    ...
    optimization: {
        minimize: false
    },
}
```

**Comment by HHH1994** [comment]
thank you bro, expect more example with specific trace detail in the future

**Comment by HHH1994** [comment]
> 

@JacksonGL thank you bro, expect more example with specific trace detail in the future

**Comment by JacksonGL** [comment]
Closing this issue for now. Let me know if you have more questions
