### ISSUE TITLE
How to go back to home using while loop

### ISSUE THREAD

**Issue by Arooba-git** [facebook/memlab#53]
Hi 👋 
I am executing Memlab on a website locally, where the home logo's click reloads the page and goes to home URL. But since Memlab does not support reload, I figured the only way I can go back to home (the initial URL), is to `page.goBack` while URL !== [home URL]:

<img width="429" alt="Screen Shot 2022-12-07 at 11 48 16 AM" src="https://user-images.githubusercontent.com/56495631/206075756-66256fc6-f480-4fa9-ba13-89ac1d1d546e.png">

but it runs into this error:
<img width="885" alt="Screen Shot 2022-12-07 at 11 49 31 AM" src="https://user-images.githubusercontent.com/56495631/206075937-8255c555-13bb-4343-b295-7e8749952b88.png">

I also tried this way
<img width="489" alt="Screen Shot 2022-12-07 at 11 42 36 AM" src="https://user-images.githubusercontent.com/56495631/206075071-440c9c0b-ef6c-421a-99a4-5e89cc39c513.png">

but same result :/
Would apprictae any guidance/help in this regard.
Cheers! ✌️

**Comment by Arooba-git** [comment]
Just to show the initial URL is the same as used in conditional expression:
<img width="639" alt="Screen Shot 2022-12-07 at 11 57 55 AM" src="https://user-images.githubusercontent.com/56495631/206077274-0cf3494e-3995-48ea-9d56-e220ebb29ac2.png">

**Comment by Arooba-git** [comment]
btw I logged the URL and it seems it does reach the specified URL.. then not sure why it ends up reloading 🤔 

<img width="751" alt="Screen Shot 2022-12-07 at 12 05 28 PM" src="https://user-images.githubusercontent.com/56495631/206078327-6b33d917-94b8-4ec9-9430-c24d3f009f5d.png">

**Comment by JacksonGL** [comment]
There are several different errors in on your console screenshots.
 1. The `ReferenceError: addRow is not defined` seems to be a bug in either Puppeteer or Chromium.
 2. When MemLab reports `Error: the page is reloaded`, it means MemLab found that the JavaScript heap has been cleared and reinitialized. So it means the web page under test reloads when `page.goBack()` is called.

To find memory leaks in MemLab, we often recommend the following test step sequence as a good practice:
```
A (url) -> B (action) -> A (back)
``` 
But when this is hard to achieve (like testing your web page), you don't really have to go back to the initial state. The MemLab `back` callback just need to make the web page reach a state where the following conditions are satisfied: 
 1. The memory allocated in `action` are expected to be released. 
 2. The JS heap is not reset (by a page reload)
Depending on the logic of the app under test,`back` could be navigating to a different page or triggering a different interaction, for Example, something like:
```
A (url) -> B (action) -> C (back)
```

**Comment by Arooba-git** [comment]
I see.. thanks for the prompt response!

btw I was wondering if it could also be due to this issue:
https://github.com/puppeteer/puppeteer/issues/257

**Comment by JacksonGL** [comment]
Looks like a different issue since Puppeteer doesn't get stuck based on your description.
