### ISSUE TITLE
How do I not save file s1.heapsnapshot, s2.heapsnapshot, s3.heapsnapshot when Run Memlab in Node.js?

### ISSUE THREAD

**Issue by zlq1997** [facebook/memlab#54]
when I use command "memlab run --scenario /path/to/test/scenario/file.js \
  --work-dir /path/to/save/memlab/run/results/", the **saved  files s1.heapsnapshot, s2.heapsnapshot, s3.heapsnapshot** occupy about 300M in local PC, it's too large for me, how can I **cancel save them**?

**Comment by JacksonGL** [comment]
MemLab needs those snapshot files to find memory leaks. You can add a `--skip-snapshot` option to when running MemLab, the option is only used for testing the e2e interaction, MemLab won't try to detect memory leaks then.

**Comment by JacksonGL** [comment]
If you mean MemLab can save heap snapshots for analysis but needs to delete the snapshots after detecting memory leaks, we can add a new flag (e.g., `--clean-up-snapshots`) to clean up afterwards.

Alternatively, you can use this bash command to clean up the snapshots:
```bash
rm -rf $(memlab get-default-work-dir)/data/cur/*.snapshot
```
