### ISSUE TITLE
[Question] Can page reload , page refresh scenarios be handled using memlab?

### ISSUE THREAD

**Issue by pranesh517** [facebook/memlab#63]
Can we handle page reload or page refresh scenarios using memlab?
I am getting below error while running scenario:
**The page is reloaded. MemLab cannot analyze heap across page reloads. Please remove window.reload() calls, page.goto() calls, or any reload logic.**

I am testing login in and going back scenario.

**Comment by JacksonGL** [comment]
If the web page is reloaded after login, the JS engine will create a new heap, so it doesn't make sense to revert to the pre-login scenario and compare the heap. Therefore, if the goal is to identify memory leaks during the login process and the tested web application reloads immediately after login, any memory leaks that happen during login are usually harmless as the page refresh destroys the entire heap.

However, if the goal is to find memory leaks during the initial page load following a login reload, I suggest using one of the following scenario templates without the `action` and `back` callback (memlab will try to find leaks in the entire heap without diffing the heap):

```javascript
const scenario = {
  url: () => ...,  // initial page load url after the login refresh
  cookies: () => [...], // cookies for the web app under test
};
module.exports = scenario;
```
For more details about the `cookies` API, please check out the [doc](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario#optional-cookies).

An alternative is to use `beforeInitialPageLoad` to log in with the Puppeteer API:
```javascript
const scenario = {
  beforeInitialPageLoad: async (page) => {
    // login with username and password here
  },
  url: () => '...', // initial page load url after the login refresh
}
module.exports = scenario;
```

**Comment by pranesh517** [comment]
@JacksonGL: may be a lame question but, how to decide whether i should use memlab or not with any particular applications. I cam see it's only for Javascript applications. Any other constraint i should be aware of?

**Comment by JacksonGL** [comment]
@pranesh517 The JavaScript application has to run on V8 (Chromium or Chrome) or Hermes. To get debuggable memory leak trace, the JS code needs be in non-minified code (or at least minified code with readable variables, function name, and property names on objects).
