### ISSUE TITLE
Can't use findLeaks API without metadata files

### ISSUE THREAD

**Issue by AndrewBarzu** [facebook/memlab#76]
Currently I have to manually generate metadata files in order to call the findLeaks API using snapshots that I manually take. It would be better if I could call the findLeaks API in the same way I would call the find-leaks CLI method, in that the API should provide the same functionalities as the CLI.

**Comment by JacksonGL** [comment]
Your suggestion makes sense. We will consider adding an API that can identify leaks without the metadata file.
