### ISSUE TITLE
/usr/bin/env: invalid option -- 'S'

### ISSUE THREAD

**Issue by balihoo-jvakotar** [facebook/memlab#78]
Node version: 16.19.0
npm: 9.6.4

Here attach screenshot for facing error:
![image](https://github.com/facebook/memlab/assets/66617390/70645173-424b-451b-96a5-9f84913c72b7)

**Comment by JacksonGL** [comment]
To quickly fix, use `vim $(which memlab)` to remove the `-S` in the shebang of the file
`#!/usr/bin/env -S node --expose-gc --max-old-space-size=4096` -> `#!/usr/bin/env node --expose-gc --max-old-space-size=4096`
Or `#!/usr/bin/env node`

If you are using a linux distro or Mac OS that is not too old, `-S` should be supported in by `env`.

**Comment by JacksonGL** [comment]
Closing since this issue cannot be replicated.
