### ISSUE TITLE
Can we skip url method in the scenario?

### ISSUE THREAD

**Issue by rupesh1306** [facebook/memlab#80]
Hi,
In scenario there are three main methods like url, action and back.
Can we skip url method or non navigation in url method?
The reason for skipping url is, we have popup and popups does not change url and for base screen we want to keep popup and then there is another popup which is going to be open from action method.
for login already using beforeInitialLoad method and from there itself we would like to open popup and then action.

**Comment by JacksonGL** [comment]
Maybe  the [`setup`](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback
) callback could be an alternative? E.g., do initial page load in the `url` callback and use `setup` to login and prepare before `action`
