### ISSUE TITLE
How to get list of files(HTML/CSS/JS) executed at app per Memlab scenario

### ISSUE THREAD

**Issue by rupesh1306** [facebook/memlab#82]
HI,
How to get list of files(HTML/CSS/JS) participated(webapp side files) in executing Memlab scenario?
Actually I would like to know impact of change at web application side, so is there any way to get that information?

Regards,
Rupesh

**Comment by JacksonGL** [comment]
Currently, Memlab supporting recording all JavaScript files that are loaded during a scenario execution. To use this feature, add the `--log-script` command-line flag when using `memlab run`. All the loaded JavaScript files will be stored in the `$(memlab get-default-work-dir)/data/cur/code/` directory. An index of these files can be found in `files.json`.
