### ISSUE TITLE
Login with redirection

### ISSUE THREAD

**Issue by karan2227** [facebook/memlab#86]
Need to run memlab on an authenticated route, How to ensure proper authentication, given the authentication process involves redirections?

I received the following error after automating the flow programmatically in the `setup` callback.
The page is reloaded. MemLab cannot analyze heap across page reloads. Please remove window reload() calls, page goto) calls, or any reload logic.

while trying the same in `beforeInitialPageLoad`, it gives interaction failure.

**Comment by JacksonGL** [comment]
> while trying the same in `beforeInitialPageLoad`, it gives interaction failure.

Can you share what interaction failure you got?

Consider using the [`cookies`](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#optional-cookies) callback to bypass the authentication process.
