### ISSUE TITLE
Analyzing/taking heap snapshots of pages that become unresponsive from extreme leaks

### ISSUE THREAD

**Issue by emmaxtung** [facebook/memlab#87]
Hi, I was wondering if there has been any testing of Memlab with pages that freeze up and go unresponsive from extreme memory leaks. I discovered a page on my web app that becomes unresponsive after an action but I've been unable to run memlab on it as it gets stuck on taking a snapshot once the page freezes. I assume this is out of memlab's control because I tried to take a snapshot manually through Chrome dev tools as well and the same thing happened. 
I tried pausing the javascript on the page to debug but the memory level in the heap snapshot does not reflect the page's memory heap in its unresponsive state as I see through Chrome task manager that the page is using up 650mb of memory whereas the memory tab shows only 130mb (which is around the same for some other pages that do not experience this freezing).

**Comment by JacksonGL** [comment]
Normally, a 650MB memory increase doesn't freeze up the page on desktop or laptop devices. Besides the memory leak, there could be a performance or correctness issue (e.g., an infinite loop) that makes the page unresponsive.
